## Apply
- hacer transformaciones avanzadas

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_csv('files/bank-additional_full.csv', index_col=0)
df.head()

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,empvarrate,conspriceidx,consconfidx,euribor3m,nremployed,y,date,latitude,longitude,contact_month,contact_year
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,married,basic 4y,0.0,0.0,0.0,telephone,261,1,999,0,nonexistent,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,agosto,2019.0
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,married,high school,NaN,0.0,0.0,telephone,149,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,septiembre,2016.0
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,married,high school,0.0,1.0,0.0,telephone,226,1,999,0,nonexistent,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,febrero,2019.0
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,married,basic 6y,0.0,0.0,0.0,telephone,151,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,noviembre,2015.0
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,married,high school,0.0,0.0,1.0,telephone,307,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,enero,2017.0

In [ ]:
def categorizar_edad(numero): 
    if numero >= 17 and numero<=25:
        return 'Joven'
    elif  numero >= 26 and numero<=39:
        return 'Adulto'
    elif  numero >= 40 and numero<=59:
        return 'Experimentada'
    else:
        return 'Mayor'
    
    ## lamda = explicar que es

In [3]:
df['age_cat'] = df["age"].apply(categorizar_edad)
df.head()

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,empvarrate,conspriceidx,consconfidx,euribor3m,nremployed,y,date,latitude,longitude,contact_month,contact_year,age_cat
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,married,basic 4y,0.0,0.0,0.0,telephone,261,1,999,0,nonexistent,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,agosto,2019.0,Mayor
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,married,high school,NaN,0.0,0.0,telephone,149,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,septiembre,2016.0,Experimentada
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,married,high school,0.0,1.0,0.0,telephone,226,1,999,0,nonexistent,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,febrero,2019.0,Adulto
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,married,basic 6y,0.0,0.0,0.0,telephone,151,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,noviembre,2015.0,Experimentada
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,married,high school,0.0,0.0,1.0,telephone,307,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,enero,2017.0,Experimentada

## Map: 
- ir valor valor y transformarlo
- transformaciones sencillas

In [6]:
df['loan'].unique() ## prestamo : 1: SI, 0:NO

array(['No', 'Si', nan], dtype=object)

In [5]:
diccionario = {0.: 'No', 1.:'Si'}
df['loan'] = df['loan'].map(diccionario)

# Replace

In [9]:
df['pdays'].unique()

array([nan,  6.,  4.,  3.,  5.,  1.,  0., 10.,  7.,  8.,  9., 11.,  2.,
       12., 13., 14., 15., 16., 21., 17., 18., 22., 25., 26., 19., 27.,
       20.])

In [8]:
import numpy as np
df['pdays'] = df['pdays'].replace(999, np.nan)