In [1]:
import pandas as pd

In [2]:
## leer xml
df_books = pd.read_xml("../datasets/books.xml", parser="etree")

In [3]:
df_books

,id,author,title,genre,price,publish_date,description
0,bk101,"Gambardella, Matthew",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications \n ...
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."
2,bk103,"Corets, Eva",Maeve Ascendant,Fantasy,5.95,2000-11-17,After the collapse of a nanotechnology \n ...
3,bk104,"Corets, Eva",Oberon's Legacy,Fantasy,5.95,2001-03-10,"In post-apocalypse England, the mysterious \n ..."
4,bk105,"Corets, Eva",The Sundered Grail,Fantasy,5.95,2001-09-10,"The two daughters of Maeve, half-sisters, \n ..."
5,bk106,"Randall, Cynthia",Lover Birds,Romance,4.95,2000-09-02,When Carla meets Paul at an ornithology \n ...
6,bk107,"Thurman, Paula",Splish Splash,Romance,4.95,2000-11-02,A deep sea diver finds true love twenty \n ...
7,bk108,"Knorr, Stefan",Creepy Crawlies,Horror,4.95,2000-12-06,"An anthology of horror stories about roaches,\..."
8,bk109,"Kress, Peter",Paradox Lost,Science Fiction,6.95,2000-11-02,After an inadvertant trip through a Heisenberg...
9,bk110,"O'Brien, Tim",Microsoft .NET: The Programming Bible,Computer,36.95,2000-12-09,Microsoft's .NET initiative is explored in \n ...
10,bk111,"O'Brien, Tim",MSXML3: A Comprehensive Guide,Computer,36.95,2000-12-01,The Microsoft MSXML3 parser is covered in \n ...
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

In [4]:
## leer json
df_one_piece = pd.read_json("../datasets/one_piece.json")

In [5]:
df_one_piece

,rank,trend,season,episode,name,start,total_votes,average_rating
0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
5,"36,209",4,1,6,Desperate Situation! Beast Tamer Mohji vs. Luffy!,1999,364,7.7

In [6]:
## las primeras filas 
df_one_piece.head(3)

,rank,trend,season,episode,name,start,total_votes,average_rating
0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7

In [7]:
## los tres ultimos
df_one_piece.tail(3)

,rank,trend,season,episode,name,start,total_votes,average_rating
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
5,"36,209",4,1,6,Desperate Situation! Beast Tamer Mohji vs. Luffy!,1999,364,7.7

In [8]:
## ejemplo 
df_one_piece.sample(4)

,rank,trend,season,episode,name,start,total_votes,average_rating
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5

In [9]:
df_one_piece.columns ## muestra el nombre de las columnas

Index(['rank', 'trend', 'season', 'episode', 'name', 'start', 'total_votes',
       'average_rating'],
      dtype='object')

In [10]:
## si algun dato es nullo
df_one_piece.isnull()

    rank  trend  season  episode   name  start  total_votes  average_rating
0  False  False   False    False  False  False        False           False
1  False  False   False    False  False  False        False           False
2  False  False   False    False  False  False        False           False
3  False  False   False    False  False  False        False           False
4  False  False   False    False  False  False        False           False
5  False  False   False    False  False  False        False           False

In [11]:
df_one_piece.isnull().sum() # para ver los nulos por columnas

rank              0
trend             0
season            0
episode           0
name              0
start             0
total_votes       0
average_rating    0
dtype: int64

In [12]:
df_one_piece.info() ## me da informacion del total de columnas si hay nulos, tipo de datos, nombre..

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rank            6 non-null      object
 1   trend           6 non-null      int64
 2   season          6 non-null      int64
 3   episode         6 non-null      int64
 4   name            6 non-null      object
 5   start           6 non-null      int64
 6   total_votes     6 non-null      int64
 7   average_rating  6 non-null      float64
dtypes: float64(1), int64(5), object(2)
memory usage: 516.0+ bytes

In [13]:
df_one_piece.describe() # mee da informacón sobre columnas numericas, estadisticos

           trend  season   episode   start  total_votes  average_rating
count   6.000000     6.0  6.000000     6.0     6.000000        6.000000
mean    8.666667     1.0  3.500000  1999.0   455.166667        7.733333
std     5.278889     0.0  1.870829     0.0   103.400999        0.206559
min     4.000000     1.0  1.000000  1999.0   364.000000        7.500000
25%     4.750000     1.0  2.250000  1999.0   384.500000        7.625000
50%     7.500000     1.0  3.500000  1999.0   438.500000        7.700000
75%    10.250000     1.0  4.750000  1999.0   467.000000        7.775000
max    18.000000     1.0  6.000000  1999.0   647.000000        8.100000

In [14]:
df_one_piece.drop_duplicates() ## bborra duplicados

,rank,trend,season,episode,name,start,total_votes,average_rating
0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
5,"36,209",4,1,6,Desperate Situation! Beast Tamer Mohji vs. Luffy!,1999,364,7.7

In [15]:
df_one_piece.dtypes ## tipo de daros de una columna

rank               object
trend               int64
season              int64
episode             int64
name               object
start               int64
total_votes         int64
average_rating    float64
dtype: object

In [16]:
df_one_piece

,rank,trend,season,episode,name,start,total_votes,average_rating
0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
5,"36,209",4,1,6,Desperate Situation! Beast Tamer Mohji vs. Luffy!,1999,364,7.7

In [17]:
df_one_piece['trend']

0    18
1    11
2     7
3     8
4     4
5     4
Name: trend, dtype: int64

In [18]:
df_one_piece['episode'].unique()

array([1, 2, 3, 4, 5, 6])

In [19]:
sum(df_one_piece['episode'])

21

In [20]:
df_one_piece.to_csv("df_final_one_piec.csv")

In [30]:
## leer un csv 
df_clientes = pd.read_csv("../datasets/clientes.csv", index_col=0) ## por defecto va a separar por ,
df_clientes

,first_name,last_name,email,gender,City,Country,Address
id,,,,,,,
1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
"5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,""Hospitalet De Llobregat, L'"",Spain,9289 Merry Circle",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
996,Ray,Tarpey,rtarpeyrn@bravesites.com,Female,Zamora,Spain,36384 Sommers Terrace
997,Flem,Roderham,froderhamro@dropbox.com,Male,Pontevedra,Spain,93177 Eastwood Parkway
998,Winifield,Blakes,wblakesrp@jiathis.com,Male,Vigo,Spain,03044 Grayhawk Road
999,Lanita,Espinosa,lespinosarq@discuz.net,Female,Dos Hermanas,Spain,2 Schmedeman Drive
1000,Grissel,Siberry,gsiberryrr@wikispaces.com,Female,Leon,Spain,42274 Waywood Terrace

In [22]:
df_clientes.head(6)

,id,first_name,last_name,email,gender,City,Country,Address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,"5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Stacy,Minchinton,sminchinton5@ameblo.jp,Male,Palma De Mallorca,Spain,4 Meadow Vale Way

In [23]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   object
 1   first_name  948 non-null    object
 2   last_name   948 non-null    object
 3   email       923 non-null    object
 4   gender      877 non-null    object
 5   City        824 non-null    object
 6   Country     800 non-null    object
 7   Address     909 non-null    object
dtypes: object(8)
memory usage: 62.6+ KB

In [24]:
df_clientes.isnull().sum()

id              0
first_name     52
last_name      52
email          77
gender        123
City          176
Country       200
Address        91
dtype: int64

In [35]:
## leer excel 
df_libros_ejemplo = pd.read_excel("../datasets/libros_ejemplo.xlsx", index_col=0)
df_libros_ejemplo

     Nombre    Autor  Precio Fecha_Publicacion
ID
1   Libro A  Autor 1   15.99        2021-05-10
2   Libro B  Autor 2   23.50        2020-11-15
3   Libro C  Autor 3   12.75        2019-06-20
4   Libro D  Autor 4    8.99        2022-02-01
5   Libro E  Autor 5   19.95        2018-09-05

In [36]:
df_libros_ejemplo.head(4)

     Nombre    Autor  Precio Fecha_Publicacion
ID
1   Libro A  Autor 1   15.99        2021-05-10
2   Libro B  Autor 2   23.50        2020-11-15
3   Libro C  Autor 3   12.75        2019-06-20
4   Libro D  Autor 4    8.99        2022-02-01

In [37]:
df_libros_ejemplo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nombre             5 non-null      object
 1   Autor              5 non-null      object
 2   Precio             5 non-null      float64
 3   Fecha_Publicacion  5 non-null      object
dtypes: float64(1), object(3)
memory usage: 200.0+ bytes

# Y si quiero guardar los datos en SQL

In [ ]:
# 1. Conectarme a SQL 
# 2. Crearle la bases de datos
# 3. Crear la tabla
# 4. Insertar esos valores en tabla

In [41]:
import mysql.connector
from mysql.connector import Error

try:
    conexion = mysql.connector.connect(
        host = "127.0.0.1", 
        user = 'root',
        password = ''
    )
    print('Conexion Exitosa')
except Error as e:
    print(e)

Conexion Exitosa

In [42]:
# 2. Crearle la bases de datos
try: 
    cursor = conexion.cursor()
    query = "CREATE DATABASE IF NOT EXISTS books"
    cursor.execute(query)
    print("Query exitosa")
except Error as e:
    print(e)

Query exitosa

In [43]:
df_books

,id,author,title,genre,price,publish_date,description
0,bk101,"Gambardella, Matthew",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications \n ...
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."
2,bk103,"Corets, Eva",Maeve Ascendant,Fantasy,5.95,2000-11-17,After the collapse of a nanotechnology \n ...
3,bk104,"Corets, Eva",Oberon's Legacy,Fantasy,5.95,2001-03-10,"In post-apocalypse England, the mysterious \n ..."
4,bk105,"Corets, Eva",The Sundered Grail,Fantasy,5.95,2001-09-10,"The two daughters of Maeve, half-sisters, \n ..."
5,bk106,"Randall, Cynthia",Lover Birds,Romance,4.95,2000-09-02,When Carla meets Paul at an ornithology \n ...
6,bk107,"Thurman, Paula",Splish Splash,Romance,4.95,2000-11-02,A deep sea diver finds true love twenty \n ...
7,bk108,"Knorr, Stefan",Creepy Crawlies,Horror,4.95,2000-12-06,"An anthology of horror stories about roaches,\..."
8,bk109,"Kress, Peter",Paradox Lost,Science Fiction,6.95,2000-11-02,After an inadvertant trip through a Heisenberg...
9,bk110,"O'Brien, Tim",Microsoft .NET: The Programming Bible,Computer,36.95,2000-12-09,Microsoft's .NET initiative is explored in \n ...
10,bk111,"O'Brien, Tim",MSXML3: A Comprehensive Guide,Computer,36.95,2000-12-01,The Microsoft MSXML3 parser is covered in \n ...
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

In [47]:
# 3. Crear la tabla
cursor.execute('use books')

query = ''' CREATE TABLE book (
            id varchar(5)primary key, 
            author varchar(20), 
            title varchar(100), 
            genre varchar(20),
            price float,
            publish_date date,
            description text
        )'''
cursor.execute(query)

In [49]:
import numpy as np

# 4. Insertar esos valores en tabla 
query_insertar = '''  insert into book (id, author, title, genre, price, publish_date, description) values (%s, %s, %s, %s, %s, %s, %s)'''

## insertando desde python a sql: nan, NaN == null 
df_clean = df_books.replace({np.nan: None, 'nan': None, 'Nan': None})
values = df_clean.values.tolist()

cursor.executemany(query_insertar, values)
conexion.commit()

print({cursor.rowcount})

{12}