# Pandas
- bibilioteca pra el analiisis y gestion de los datosbasados en los arrays de Numpy
- Numpy biblioteca para trabajar con arrays, numeros (listas)
- Ficheros: excel, cvs, json...

In [36]:
import pandas as pd 
pd.set_option('display.max_columns', None)

In [2]:
## crear dataframe: a partir de un fichero, a partir de un diccionario

data = {
    'Nombre': ['Ana', 'Bea', 'Teresa'], 
    'Edad': [24, 30, 18], 
    'Ciudad': ['Madrid', 'Barcelona', 'Sevilla']
}

In [3]:
df = pd.DataFrame(data)
df

   Nombre  Edad     Ciudad
0     Ana    24     Madrid
1     Bea    30  Barcelona
2  Teresa    18    Sevilla

In [4]:
data_lista = [
   {'Nombre': 'Ana', 'Edad': 25, 'Ciudad': 'Madrid'}, 
    {'Nombre': 'Bea', 'Edad': 39, 'Ciudad': 'Madrid'},
     {'Nombre': 'Teresa', 'Edad': 13, 'Ciudad': 'Madrid'}
]

df_lista = pd.DataFrame(data_lista)
df_lista

   Nombre  Edad  Ciudad
0     Ana    25  Madrid
1     Bea    39  Madrid
2  Teresa    13  Madrid

In [8]:
df = pd.read_csv("datasets/data.csv", index_col=['Day'])
df

    Weather  Temperature  Wind  Humidity
Day
Mon   Sunny        12.79    13        30
Tue   Sunny        19.67    28        96
Wed   Sunny        17.51    16        20
Thu  Cloudy        14.44    11        22
Fri  Shower        10.51    26        79
Sat  Shower        11.07    27        62
Sun   Sunny        17.50    20        10

In [33]:
## imsertar: crear columna en una posición specifica
df.insert(0, "Indice", range(1,8))
df

     Indice Weather  Temperature  Wind  Humidity  Farenheit
Day
Mon       1   Sunny        12.79    13        30     55.022
Tue       2   Sunny        19.67    28        96     67.406
Wed       3   Sunny        17.51    16        20     63.518
Thu       4  Cloudy        14.44    11        22     57.992
Fri       5  Shower        10.51    26        79     50.918
Sat       6  Shower        11.07    27        62     51.926
Sun       7   Sunny        17.50    20        10     63.500

In [32]:
## crear un df a partir de otro 
df_new = df.assign(temp_f =(df.Temperature * 9/5)+32 )
df_new

    Weather  Temperature  Wind  Humidity  Farenheit  temp_f
Day
Mon   Sunny        12.79    13        30     55.022  55.022
Tue   Sunny        19.67    28        96     67.406  67.406
Wed   Sunny        17.51    16        20     63.518  63.518
Thu  Cloudy        14.44    11        22     57.992  57.992
Fri  Shower        10.51    26        79     50.918  50.918
Sat  Shower        11.07    27        62     51.926  51.926
Sun   Sunny        17.50    20        10     63.500  63.500

In [31]:
## crear columnas nuevas en un df
df['Farenheit']= (df.Temperature * 9/5)+32
df

    Weather  Temperature  Wind  Humidity  Farenheit
Day
Mon   Sunny        12.79    13        30     55.022
Tue   Sunny        19.67    28        96     67.406
Wed   Sunny        17.51    16        20     63.518
Thu  Cloudy        14.44    11        22     57.992
Fri  Shower        10.51    26        79     50.918
Sat  Shower        11.07    27        62     51.926
Sun   Sunny        17.50    20        10     63.500

In [30]:
df_playa = df.loc[(df.Temperature > 12) & (df.Weather == "Sunny"),:]
df_playa

    Weather  Temperature  Wind  Humidity
Day
Mon   Sunny        12.79    13        30
Tue   Sunny        19.67    28        96
Wed   Sunny        17.51    16        20
Sun   Sunny        17.50    20        10

In [ ]:
## aplicar condiciones
df_mayor_12 = df.loc[df.Temperature> 12, :] 
df_mayor_12

    Weather  Temperature  Wind  Humidity
Day
Mon   Sunny        12.79    13        30
Tue   Sunny        19.67    28        96
Wed   Sunny        17.51    16        20
Thu  Cloudy        14.44    11        22
Sun   Sunny        17.50    20        10

In [27]:
# temperature, viento y la humedad que hizo el martes y el sabado
df.loc[['Tue', 'Sat'], 'Temperature':'Humidity']
df.iloc[[1,5], 1:4]

     Temperature  Wind  Humidity
Day
Tue        19.67    28        96
Sat        11.07    27        62

In [24]:
# el viento y la humedad que hizo el martes y el sabado
df.loc[['Tue', 'Sat'], ['Wind', 'Humidity']]
df.iloc[[1,5], [2,3]]

     Wind  Humidity
Day
Tue    28        96
Sat    27        62

In [23]:
# el viento que hizo el martes y el sabado
df.loc[['Tue', 'Sat'], 'Wind']
df.iloc[[1,5], 2]

Day
Tue    28
Sat    27
Name: Wind, dtype: int64

In [21]:
## el viento de toda la semana
df.loc[:,'Wind']
df.iloc[:,2]

Day
Mon    13
Tue    28
Wed    16
Thu    11
Fri    26
Sat    27
Sun    20
Name: Wind, dtype: int64

In [19]:
## Condiciones climáticas del martes
df.loc['Tue']
df.iloc[1]

Weather        Sunny
Temperature    19.67
Wind              28
Humidity          96
Name: Tue, dtype: object

In [16]:
## loc / iloc
## loc para buscar por etiquetas
## iloc para buscar por indexes
## [filas, columnas]

## saber la humedad del martes
print(df.loc['Tue', 'Humidity'])

96

In [15]:
df.iloc[1,3]

96

In [13]:
df.sample()

    Weather  Temperature  Wind  Humidity
Day
Sun   Sunny         17.5    20        10

In [37]:
## leer fichero
df_rating = pd.read_csv("datasets/rating-and-performance.csv", index_col=0)
df_rating

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,50,Livraison standard,4,0,34,50,1.0,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,50,Livraison standard,2,0,41,50,1.0,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,4.0,2.0,0.0,3.0,0,0,0,0,"Summer,cardigan,women beachwear,chiffon,Sexy w...",leopardprint,XS,1,Livraison standard,3,0,36,50,1.0,Quantité limitée !,CN,hxt520,hxt520,86 % avis positifs (295 notes),295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,119.0,87.0,42.0,36.0,0,0,0,0,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",black,M,50,Livraison standard,2,0,41,50,NaN,NaN,CN,allenfan,allenfan,"(23,832 notes)",23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,4.0,2.0,2.0,6.0,0,0,0,0,"Summer,Plus Size,Lace,Casual pants,Bottom,pant...",yellow,S,1,Livraison standard,1,0,35,50,1.0,Quantité limitée !,CN,youngpeopleshop,happyhorses,"85 % avis positifs (14,482 notes)",14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,EUR,10000,1,4.08,1367,722.0,293.0,185.0,77.0,90.0,0,0,0,0,"bohemia,Plus Size,dandelionfloralprinted,short...",navyblue,S,50,Livraison standard,2,0,41,50,NaN,NaN,CN,cxuelin99126,cxuelin99126,"90 % avis positifs (5,316 notes)",5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,EUR,100,1,3.07,28,11.0,3.0,1.0,3.0,10.0,0,0,0,0,"Summer,Panties,Elastic,Lace,Casual pants,casua...",lightblue,S,2,Livraison standard,1,0,26,50,1.0,Quantité limitée !,CN,sell best quality goods,sellbestqualitygoods,"(4,435 notes)",4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,EUR,100,0,3.71,59,24.0,15.0,8.0,3.0,9.0,0,0,0,0,"runningshort,Beach Shorts,beachpant,menbeachsh...",white,SIZE S,15,Livraison standard,2,0,11,50,NaN,NaN,CN,shixueying,shixueying,86 % avis positifs (210 notes),210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,2.50,2,0.0,1.0,0.0,0.0,1.0,0,0,0,0,"Summer,fashion women,Fashion,Lace,Dresses,Dres...",white,Size S.,36,Livraison standard,3,0,29,50,NaN,NaN,CN,modai,modai,77 % avis positifs (31 notes),31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,4.07,14,8.0,3.0,1.0,0.0,2.0,0,0,0,0,"Summer,Leggings,slim,Yoga,pants,Slim Fit,Women...",red,S,50,Livraison standard,2,0,41,50,NaN,NaN,CN,AISHOPPINGMALL,aishoppingmall,"90 % avis positifs (7,023 notes)",7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [40]:
df_rating.insert(2, "Diferencia_precios", (df_rating.price - df_rating.retail_price))
df_rating.head(3)

,title,title_orig,Diferencia_precios,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,2.0,16.0,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,50,Livraison standard,4,0,34,50,1.0,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,-14.0,8.0,22,EUR,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,50,Livraison standard,2,0,41,50,1.0,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,-35.0,8.0,43,EUR,100,0,3.57,14,5.0,4.0,2.0,0.0,3.0,0,0,0,0,"Summer,cardigan,women beachwear,chiffon,Sexy w...",leopardprint,XS,1,Livraison standard,3,0,36,50,1.0,Quantité limitée !,CN,hxt520,hxt520,86 % avis positifs (295 notes),295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08

In [39]:
df_rating.columns

Index(['title', 'title_orig', 'price', 'retail_price', 'currency_buyer',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='object')

## Series
- un lista de datos, mismo tipo de datos
- tienen un indice
-  values: no sdevuelve el valor de las seires
- size: numero total de elemnetos.

In [41]:
serie_vacia = pd.Series()
serie_vacia

/var/folders/cr/f3dqyy756z9ftxxsrmgtgjjh0000gn/T/ipykernel_7154/1795272496.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  serie_vacia = pd.Series()

Series([], dtype: float64)

In [42]:
# crear una serie a partir d euna lista
lista = [23, 45, 78, 98]
serie_lista = pd.Series(lista)
serie_lista

0    23
1    45
2    78
3    98
dtype: int64

In [43]:
lista

[23, 45, 78, 98]

In [44]:
serie = pd.Series(range(1,8))
serie

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [45]:
serie.index = range(2,9)
serie

2    1
3    2
4    3
5    4
6    5
7    6
8    7
dtype: int64

In [46]:
dias = ['l', 'm', 'm', 'j', 'v', 's', 'd']
serie.index = dias
serie

l    1
m    2
m    3
j    4
v    5
s    6
d    7
dtype: int64

In [47]:
serie.values

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
serie.index

Index(['l', 'm', 'm', 'j', 'v', 's', 'd'], dtype='object')

In [49]:
serie.dtype

dtype('int64')

In [50]:
serie.size

7

In [51]:
serie.shape

(7,)

In [52]:
serie

l    1
m    2
m    3
j    4
v    5
s    6
d    7
dtype: int64

In [53]:
serie['l']

1

In [54]:
serie.loc['l']

1

In [55]:
serie.iloc[0]

1

In [56]:
# crear una serie a partir de un fichero 
df_residuos = pd.read_json("datasets/residuos.json")
df_residuos

                                                  data
0    {'residuos_pelig_cantidad_ton': 23476.42, 'res...
1    {'residuos_pelig_cantidad_ton': 1927.25, 'resi...
2    {'residuos_pelig_cantidad_ton': 25333.54, 'res...
3    {'residuos_pelig_cantidad_ton': 22060.07, 'res...
4    {'residuos_pelig_cantidad_ton': 13109.74, 'res...
..                                                 ...
98   {'residuos_pelig_cantidad_ton': 5931.83, 'resi...
99   {'residuos_pelig_cantidad_ton': 11804.08, 'res...
100  {'residuos_pelig_cantidad_ton': 6425.61, 'resi...
101  {'residuos_pelig_cantidad_ton': 47419.86, 'res...
102  {'residuos_pelig_cantidad_ton': 4905.3, 'resid...

[103 rows x 1 columns]

In [57]:
df_residuos_2 = df_residuos.data.apply(pd.Series)
df_residuos_2

,residuos_pelig_cantidad_ton,residuos_pelig_año,residuos_pelig_opcion_gestion,residuos_pelig_tratamiento
0,23476.42,2012,Reciclado,Recuperación de disolventes
1,1927.25,2012,Reciclado,Recuperación de metales
2,25333.54,2012,Reciclado,Regeneración de aceite
3,22060.07,2012,Tratamiento previo a otras formas de valorización,Trituración previa a valorización de baterías
4,13109.74,2012,Tratamiento previo a otras formas de valorización,Operaciones previas a valorización de RAEE
...,...,...,...,...
98,5931.83,2018,Eliminación,Esterilización
99,11804.08,2018,Eliminación,Evapocondensación
100,6425.61,2018,Eliminación,Tratamiento físico-químico
101,47419.86,2018,Eliminación,Vertido en depósito de seguridad
102,4905.30,2018,Eliminación,Tratamiento biológico