## Union de datos
- cargar datos de diferentes ficheros (csv, excel)
- obtener un unico df con toda esa información

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('./files/bank-additional.csv', index_col=0)
df.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [3]:
df_2012 = pd.read_excel('files/customer-details.xlsx', sheet_name='2012', index_col=0)
df_2013 = pd.read_excel('files/customer-details.xlsx', sheet_name='2013', index_col=0)
df_2014 = pd.read_excel('files/customer-details.xlsx', sheet_name='2014', index_col=0)

## Concat

In [4]:
df_años = pd.concat([df_2012, df_2013, df_2014], axis=0) ## join= "outer", join="inner"
df_años.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [5]:
df_años.shape

(43170, 6)

# Merge
Unir df por columnas en común

In [6]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')

In [7]:
df_años.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')

In [8]:
df['id_'].unique()

array(['089b39d8-e4d0-461b-87d4-814d71e0e079',
       'e9d37224-cb6f-4942-98d7-46672963d097',
       '3f9f49b5-e410-4948-bf6e-f9244f04918b', ...,
       'cadadd4b-7ee5-4019-b13a-ca01bb67ca5b',
       '5f432048-d515-4bb5-9c94-62db451f88d4',
       '993bbbd6-4dbc-4a40-a408-f91f8462bee6'], dtype=object)

In [9]:
df_años['ID'].unique()

array(['089b39d8-e4d0-461b-87d4-814d71e0e079',
       'e9d37224-cb6f-4942-98d7-46672963d097',
       '3f9f49b5-e410-4948-bf6e-f9244f04918b', ...,
       'd6271666-319d-42c8-a741-cb22bf2c2093',
       'f67fbfa8-6573-414d-a805-b26a2f1b1ceb',
       '9727bc06-c11a-461a-a5bb-3d210467cc2a'], dtype=object)

In [10]:
df_merge = df_años.merge(df, left_on='ID', right_on='id_', how='left') # how= "left", how='right'
df_merge.tail()
## inner join por defecto

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
43165,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4,NaN,admin.,MARRIED,university.degree,NaN,0.0,0.0,cellular,674.0,3.0,999.0,0.0,NONEXISTENT,1.4,"93,918","-42,7","4,958","5228,1",no,23-septiembre-2019,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
43166,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6,NaN,unemployed,SINGLE,university.degree,0.0,0.0,1.0,cellular,104.0,2.0,999.0,0.0,NONEXISTENT,-0.1,"93,2",-42,"4,021","5195,8",no,6-noviembre-2019,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43168,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43169,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_final = df_merge.copy()

### Limpieza de datos:
- "quitar la paja"
- Quitar duplicados
- quitar vacios,, nulos? -- Gestión
- Eliminar columnas innecesafias, redudanres
- homogennizar nombres de columnas (Nombre, apellidos, ciudad_Nacimiento, fecha de nacimientos)
- Cambio de tipos de daros
- normalizar valores categoricos(Estado civil: Married, Casado, D, Divorcied )
- cambiar valores problemáticos (caracteres)
- Creación nuevas columnas

In [13]:
df_final.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'duration', 'campaign', 'pdays', 'previous',
       'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'y', 'date', 'latitude', 'longitude',
       'id_'],
      dtype='object')

In [15]:
df_final.drop('id_', axis= 1 ,inplace=True)
df_final.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'duration', 'campaign', 'pdays', 'previous',
       'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'y', 'date', 'latitude', 'longitude'],
      dtype='object')

In [16]:
nuevas_columnas = {}
for col in df_final.columns:
    nuevas_columnas[col] = col.lower().replace(".", "_")

nuevas_columnas

{'Income': 'income',
 'Kidhome': 'kidhome',
 'Teenhome': 'teenhome',
 'Dt_Customer': 'dt_customer',
 'NumWebVisitsMonth': 'numwebvisitsmonth',
 'ID': 'id',
 'age': 'age',
 'job': 'job',
 'marital': 'marital',
 'education': 'education',
 'default': 'default',
 'housing': 'housing',
 'loan': 'loan',
 'contact': 'contact',
 'duration': 'duration',
 'campaign': 'campaign',
 'pdays': 'pdays',
 'previous': 'previous',
 'poutcome': 'poutcome',
 'emp.var.rate': 'emp_var_rate',
 'cons.price.idx': 'cons_price_idx',
 'cons.conf.idx': 'cons_conf_idx',
 'euribor3m': 'euribor3m',
 'nr.employed': 'nr_employed',
 'y': 'y',
 'date': 'date',
 'latitude': 'latitude',
 'longitude': 'longitude'}

In [17]:
df_final.rename(columns=nuevas_columnas, inplace=True)
df_final.columns

Index(['income', 'kidhome', 'teenhome', 'dt_customer', 'numwebvisitsmonth',
       'id', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'duration', 'campaign', 'pdays', 'previous',
       'poutcome', 'emp_var_rate', 'cons_price_idx', 'cons_conf_idx',
       'euribor3m', 'nr_employed', 'y', 'date', 'latitude', 'longitude'],
      dtype='object')

In [18]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43170 entries, 0 to 43169
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   income             43170 non-null  int64
 1   kidhome            43170 non-null  int64
 2   teenhome           43170 non-null  int64
 3   dt_customer        43170 non-null  datetime64[ns]
 4   numwebvisitsmonth  43170 non-null  int64
 5   id                 43170 non-null  object
 6   age                37880 non-null  float64
 7   job                42655 non-null  object
 8   marital            42915 non-null  object
 9   education          41193 non-null  object
 10  default            34019 non-null  float64
 11  housing            41974 non-null  float64
 12  loan               41974 non-null  float64
 13  contact            43000 non-null  object
 14  duration           43000 non-null  float64
 15  campaign           43000 non-null  float64
 16  pdays              43000 non-null  float64
 17  previous           43000 non-null  float64
 18  poutcome           43000 non-null  object
 19  emp_var_rate       43000 non-null  float64
 20  cons_price_idx     42529 non-null  object
 21  cons_conf_idx      43000 non-null  object
 22  euribor3m          33744 non-null  object
 23  nr_employed        43000 non-null  object
 24  y                  43000 non-null  object
 25  date               42752 non-null  object
 26  latitude           43000 non-null  float64
 27  longitude          43000 non-null  float64
dtypes: datetime64[ns](1), float64(11), int64(4), object(12)
memory usage: 10.6+ MB

In [ ]:
df_final["age"] = pd.to_numeric(df_final["age"], errors="coerce") ## ?buscar como poner exactamente en int

cambiar_numerico = ['age', 'euribor3m', 'nr_employed']
for col in cambiar_numerico: 
    df_final[col] = pd.to_numeric(df_final[col], errors="coerce")

df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43170 entries, 0 to 43169
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   income             43170 non-null  int64
 1   kidhome            43170 non-null  int64
 2   teenhome           43170 non-null  int64
 3   dt_customer        43170 non-null  datetime64[ns]
 4   numwebvisitsmonth  43170 non-null  int64
 5   id                 43170 non-null  object
 6   age                37880 non-null  float64
 7   job                42655 non-null  object
 8   marital            42915 non-null  object
 9   education          41193 non-null  object
 10  default            34019 non-null  float64
 11  housing            41974 non-null  float64
 12  loan               41974 non-null  float64
 13  contact            43000 non-null  object
 14  duration           43000 non-null  float64
 15  campaign           43000 non-null  float64
 16  pdays              43000 non-null  float64
 17  previous           43000 non-null  float64
 18  poutcome           43000 non-null  object
 19  emp_var_rate       43000 non-null  float64
 20  cons_price_idx     42529 non-null  object
 21  cons_conf_idx      43000 non-null  object
 22  euribor3m          15 non-null     float64
 23  nr_employed        8020 non-null   float64
 24  y                  43000 non-null  object
 25  date               42752 non-null  object
 26  latitude           43000 non-null  float64
 27  longitude          43000 non-null  float64
dtypes: datetime64[ns](1), float64(13), int64(4), object(10)
memory usage: 10.6+ MB

In [28]:
## automatizarlo
## 1- buscar las columnas categoricas
## 2- imprimir los valors de esa columnas categoria

for col in df_final.select_dtypes(include=['object']):
    print(col)
    print(df_final[col].unique())

id
['089b39d8-e4d0-461b-87d4-814d71e0e079'
 'e9d37224-cb6f-4942-98d7-46672963d097'
 '3f9f49b5-e410-4948-bf6e-f9244f04918b' ...
 'd6271666-319d-42c8-a741-cb22bf2c2093'
 'f67fbfa8-6573-414d-a805-b26a2f1b1ceb'
 '9727bc06-c11a-461a-a5bb-3d210467cc2a']
job
['housemaid' 'services' 'admin' 'blue-collar' 'technician' 'retired'
 'management' 'unemployed' 'self-employed' nan 'entrepreneur' 'student']
marital
['MARRIED' 'SINGLE' 'DIVORCED' nan]
education
['basic.4y' 'high.school' 'basic.6y' 'basic.9y' 'professional.course' nan
 'university.degree' 'illiterate']
contact
['telephone' nan 'cellular']
poutcome
['NONEXISTENT' nan 'FAILURE' 'SUCCESS']
cons_price_idx
['93,994' nan '94,465' '93,918' '93,444' '93,798' '93,2' '92,756' '92,843'
 '93,075' '92,893' '92,963' '92,469' '92,201' '92,379' '92,431' '92,649'
 '92,713' '93,369' '93,749' '93,876' '94,055' '94,215' '94,027' '94,199'
 '94,601' '94,767']
cons_conf_idx
['-36,4' nan '-41,8' '-42,7' '-36,1' '-40,4' '-42' '-45,9' '-50' '-47,1'
 '-46,2' '-40,8' '-33,6' '-31,4' '-29,8' '-26,9' '-30,1' '-33' '-34,8'
 '-34,6' '-40' '-39,8' '-40,3' '-38,3' '-37,5' '-49,5' '-50,8']
y
['no' 'yes' nan]
date
['2-agosto-2019' '14-septiembre-2016' '15-febrero-2019' ... '28-mayo-2016'
 '22-abril-2015' '7-marzo-2015']

In [24]:
## homogenizr los valores dentro de las columas categoricas
df_final['marital'].unique()

array(['MARRIED', 'SINGLE', 'DIVORCED', nan], dtype=object)

In [ ]:
df_final['job'] = df_final['job'].str.replace(".", "") #? acepta expresiones regulares??
df_final['marital'] = df_final['marital'].str.lower()

/var/folders/cr/f3dqyy756z9ftxxsrmgtgjjh0000gn/T/ipykernel_6062/3643250282.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_final['job'] = df_final['job'].str.replace(".", "")