## Union de datos
- cargar datos de diferentes ficheros (csv, excel)
- obtener un unico df con toda esa información

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('./files/bank-additional.csv', index_col=0)
df.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [6]:
df_2012 = pd.read_excel('files/customer-details.xlsx', sheet_name='2012', index_col=0)
df_2013 = pd.read_excel('files/customer-details.xlsx', sheet_name='2013', index_col=0)
df_2014 = pd.read_excel('files/customer-details.xlsx', sheet_name='2014', index_col=0)

In [7]:
df_2012.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [8]:
df_2013.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

In [9]:
df_2014.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942

In [10]:
df_2012.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')

In [11]:
df_2013.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')

In [12]:
df_2012.shape

(20115, 6)

In [13]:
df_2013.shape

(8965, 6)

In [14]:
df_2014.shape

(14090, 6)

## Concat

In [17]:
df_años = pd.concat([df_2012, df_2013, df_2014], axis=0) ## join= "outer", join="inner"
df_años.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [19]:
df_años.shape

(43170, 6)

# Merge
Unir df por columnas en común

In [20]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')

In [21]:
df_años.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')

In [29]:
df['id_'].unique()

array(['089b39d8-e4d0-461b-87d4-814d71e0e079',
       'e9d37224-cb6f-4942-98d7-46672963d097',
       '3f9f49b5-e410-4948-bf6e-f9244f04918b', ...,
       'cadadd4b-7ee5-4019-b13a-ca01bb67ca5b',
       '5f432048-d515-4bb5-9c94-62db451f88d4',
       '993bbbd6-4dbc-4a40-a408-f91f8462bee6'], dtype=object)

In [30]:
df_años['ID'].unique()

array(['089b39d8-e4d0-461b-87d4-814d71e0e079',
       'e9d37224-cb6f-4942-98d7-46672963d097',
       '3f9f49b5-e410-4948-bf6e-f9244f04918b', ...,
       'd6271666-319d-42c8-a741-cb22bf2c2093',
       'f67fbfa8-6573-414d-a805-b26a2f1b1ceb',
       '9727bc06-c11a-461a-a5bb-3d210467cc2a'], dtype=object)

In [28]:
df_merge = df_años.merge(df, left_on='ID', right_on='id_', how='left') # how= "left", how='right'
df_merge.tail()
## inner join por defecto

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
43165,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4,NaN,admin.,MARRIED,university.degree,NaN,0.0,0.0,cellular,674.0,3.0,999.0,0.0,NONEXISTENT,1.4,"93,918","-42,7","4,958","5228,1",no,23-septiembre-2019,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
43166,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6,NaN,unemployed,SINGLE,university.degree,0.0,0.0,1.0,cellular,104.0,2.0,999.0,0.0,NONEXISTENT,-0.1,"93,2",-42,"4,021","5195,8",no,6-noviembre-2019,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43168,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43169,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_años.shape

(43170, 6)

In [25]:
df.shape

(43000, 23)

In [27]:
df_merge.shape

(43170, 29)

# Joins
- merge union a columans iguales
- join  union a traves de indices

In [31]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')

In [ ]:
## renombrar columnas
df.rename(columns={'id_': 'ID'}, inplace=True)

In [33]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'ID'],
      dtype='object')

In [34]:
df.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [35]:
df.set_index(['ID'], inplace=True)
df.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
ID,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463

In [39]:
df_años.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

In [44]:
df_años.set_index(['Income'], inplace=True)

In [42]:
df_join = df_años.join(df, on='ID') # por defecto hace un how="left"
df_join.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233
e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923
3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847
9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463

In [43]:
df_join.shape

(43170, 27)